# Checkmarx DAST

name: Dast-API
on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Scan with Checkmarx DAST
    - name: run cxdast API 
      uses: checkmarx/dast-github-action@v1.0.2
      env: 
        CX_APIKEY: ${{ secrets.CXONE_CANARY_APIKEY }}
      with:
        command: api
        config: ./dast-config/api.yaml
        environment_id: 085a9321-d79e-4cd7-a154-0f27fdea7956
        openapi: ./swagger/openapi.json
        #project_id: b03ebbb9-2bda-48dd-b6e0-8b6897c301f2
        base_url: https://deu.ast.checkmarx.net/
        # fail_on: 'HIGH'
        verbose: true
        output: ./output
    - name: Reclaim output directory
      if: always()  
      run: sudo chown -R 1001:1001 ${{ github.workspace }}/output
    - uses: actions/upload-artifact@v3
      if: always()
      name: Attach DAST report as an artifact to workflow  
      with:
        name: report
        path: ./output        
